# Generated by Django 5.2.1 on 2025-06-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributekey',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
