# Generated by Django 5.2.1 on 2025-06-03 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_attributekey_key_alter_attributevalue_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='attribute_key',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='attribute_value',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
        ),
    ]
