# Generated by Django 5.2.1 on 2025-06-03 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_rename_attribute_key_productattribute_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='key',
            new_name='attribute_key',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='value',
            new_name='attribute_value',
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='ecommerce.product'),
        ),
    ]
